name: Workflow 2

on:
  push:
    branches:
      - master

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print message
        run: |
          echo "Workflow 2 was executed"
          echo "Secret: ${{ secrets.SECRET_1 }}"
          echo "Environment Variable: ${{ vars.ENV_1 }}"