name: Workflow 1

on:
  push:
    branches:
      - master

jobs:
  print-message:
    environment: master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print message
        env:
          ENV_1: ${{ vars.ENV_1 }}
          SECRET_1: ${{ secrets.SECRET_1 }}
        run: |
          echo "Workflow 1 was executed"
          echo "Secret: $SECRET_1"
          echo "Environment Variable: $ENV_1"